/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_jggmsg_WRAP_H_
#define SWIG_jggmsg_WRAP_H_

class SwigDirector_ChannelListener : public ChannelListener, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ChannelListener(JNIEnv *jenv);
    virtual void OnPositiveConnect(int nServiceID, int nConnectID);
    virtual void OnPositiveDisConnect(int nServiceID, int nConnectID);
    virtual void OnPassiveConnect(int nSeviceID, int nConnectID);
    virtual void OnPassiveDisConnect(int nServiceID, int nConnectID);
    virtual void OnReceiveMsg(int nServiceID, int nConnectID, char const *pData, int nDataLen);
public:
    bool swig_overrides(int n) {
      return (n < 5 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<5> swig_override;
};


#endif
