/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jggmsg;

public class ChannelListener {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ChannelListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChannelListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jggmsgJNI.delete_ChannelListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    jggmsgJNI.ChannelListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    jggmsgJNI.ChannelListener_change_ownership(this, swigCPtr, true);
  }

  public void OnPositiveConnect(int nServiceID, int nConnectID) {
    if (getClass() == ChannelListener.class) jggmsgJNI.ChannelListener_OnPositiveConnect(swigCPtr, this, nServiceID, nConnectID); else jggmsgJNI.ChannelListener_OnPositiveConnectSwigExplicitChannelListener(swigCPtr, this, nServiceID, nConnectID);
  }

  public void OnPositiveDisConnect(int nServiceID, int nConnectID) {
    if (getClass() == ChannelListener.class) jggmsgJNI.ChannelListener_OnPositiveDisConnect(swigCPtr, this, nServiceID, nConnectID); else jggmsgJNI.ChannelListener_OnPositiveDisConnectSwigExplicitChannelListener(swigCPtr, this, nServiceID, nConnectID);
  }

  public void OnPassiveConnect(int nSeviceID, int nConnectID) {
    if (getClass() == ChannelListener.class) jggmsgJNI.ChannelListener_OnPassiveConnect(swigCPtr, this, nSeviceID, nConnectID); else jggmsgJNI.ChannelListener_OnPassiveConnectSwigExplicitChannelListener(swigCPtr, this, nSeviceID, nConnectID);
  }

  public void OnPassiveDisConnect(int nServiceID, int nConnectID) {
    if (getClass() == ChannelListener.class) jggmsgJNI.ChannelListener_OnPassiveDisConnect(swigCPtr, this, nServiceID, nConnectID); else jggmsgJNI.ChannelListener_OnPassiveDisConnectSwigExplicitChannelListener(swigCPtr, this, nServiceID, nConnectID);
  }

  public void OnReceiveMsg(int nServiceID, int nConnectID, byte[] pData) {
    if (getClass() == ChannelListener.class) jggmsgJNI.ChannelListener_OnReceiveMsg(swigCPtr, this, nServiceID, nConnectID, pData); else jggmsgJNI.ChannelListener_OnReceiveMsgSwigExplicitChannelListener(swigCPtr, this, nServiceID, nConnectID, pData);
  }

  public ChannelListener() {
    this(jggmsgJNI.new_ChannelListener(), true);
    jggmsgJNI.ChannelListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
