/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jggmsg;

public class ChannelNode {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ChannelNode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ChannelNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jggmsgJNI.delete_ChannelNode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static ChannelNode Create(ChannelListener pListener) {
    long cPtr = jggmsgJNI.ChannelNode_Create(ChannelListener.getCPtr(pListener), pListener);
    return (cPtr == 0) ? null : new ChannelNode(cPtr, false);
  }

  public static void Destory(ChannelNode pNode) {
    jggmsgJNI.ChannelNode_Destory(ChannelNode.getCPtr(pNode), pNode);
  }

  public void Start(int nServiceID, short port) {
    jggmsgJNI.ChannelNode_Start(swigCPtr, this, nServiceID, port);
  }

  public void Stop() {
    jggmsgJNI.ChannelNode_Stop(swigCPtr, this);
  }

  public boolean Connect(String strHost, short sPort) {
    return jggmsgJNI.ChannelNode_Connect(swigCPtr, this, strHost, sPort);
  }

  public int GetServiceID() {
    return jggmsgJNI.ChannelNode_GetServiceID(swigCPtr, this);
  }

  public boolean SendToService(int nServiceID, byte[] pData) {
    return jggmsgJNI.ChannelNode_SendToService(swigCPtr, this, nServiceID, pData);
  }

  public boolean SendToAllService(byte[] pData) {
    return jggmsgJNI.ChannelNode_SendToAllService(swigCPtr, this, pData);
  }

  public boolean SendToConnect(int nConnectID, byte[] pData) {
    return jggmsgJNI.ChannelNode_SendToConnect(swigCPtr, this, nConnectID, pData);
  }

}
