/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jggmsg;

public class ggmsgJNI {
  public final static native void ChannelListener_OnPositiveConnect(long jarg1, ChannelListener jarg1_, int jarg2, int jarg3);
  public final static native void ChannelListener_OnPositiveConnectSwigExplicitChannelListener(long jarg1, ChannelListener jarg1_, int jarg2, int jarg3);
  public final static native void ChannelListener_OnPositiveDisConnect(long jarg1, ChannelListener jarg1_, int jarg2, int jarg3);
  public final static native void ChannelListener_OnPositiveDisConnectSwigExplicitChannelListener(long jarg1, ChannelListener jarg1_, int jarg2, int jarg3);
  public final static native void ChannelListener_OnPassiveConnect(long jarg1, ChannelListener jarg1_, int jarg2, int jarg3);
  public final static native void ChannelListener_OnPassiveConnectSwigExplicitChannelListener(long jarg1, ChannelListener jarg1_, int jarg2, int jarg3);
  public final static native void ChannelListener_OnPassiveDisConnect(long jarg1, ChannelListener jarg1_, int jarg2, int jarg3);
  public final static native void ChannelListener_OnPassiveDisConnectSwigExplicitChannelListener(long jarg1, ChannelListener jarg1_, int jarg2, int jarg3);
  public final static native void ChannelListener_OnReceiveMsg(long jarg1, ChannelListener jarg1_, int jarg2, int jarg3, byte[] jarg4);
  public final static native void ChannelListener_OnReceiveMsgSwigExplicitChannelListener(long jarg1, ChannelListener jarg1_, int jarg2, int jarg3, byte[] jarg4);
  public final static native long new_ChannelListener();
  public final static native void delete_ChannelListener(long jarg1);
  public final static native void ChannelListener_director_connect(ChannelListener obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void ChannelListener_change_ownership(ChannelListener obj, long cptr, boolean take_or_release);
  public final static native long ChannelNode_Create(long jarg1, ChannelListener jarg1_);
  public final static native void ChannelNode_Destory(long jarg1, ChannelNode jarg1_);
  public final static native void ChannelNode_Start(long jarg1, ChannelNode jarg1_, int jarg2, short jarg3);
  public final static native void ChannelNode_Stop(long jarg1, ChannelNode jarg1_);
  public final static native boolean ChannelNode_Connect(long jarg1, ChannelNode jarg1_, String jarg2, short jarg3);
  public final static native int ChannelNode_GetServiceID(long jarg1, ChannelNode jarg1_);
  public final static native boolean ChannelNode_SendToService(long jarg1, ChannelNode jarg1_, int jarg2, byte[] jarg3);
  public final static native boolean ChannelNode_SendToAllService(long jarg1, ChannelNode jarg1_, byte[] jarg2);
  public final static native boolean ChannelNode_SendToConnect(long jarg1, ChannelNode jarg1_, int jarg2, byte[] jarg3);
  public final static native void delete_ChannelNode(long jarg1);

  public static void SwigDirector_ChannelListener_OnPositiveConnect(ChannelListener jself, int nServiceID, int nConnectID) {
    jself.OnPositiveConnect(nServiceID, nConnectID);
  }
  public static void SwigDirector_ChannelListener_OnPositiveDisConnect(ChannelListener jself, int nServiceID, int nConnectID) {
    jself.OnPositiveDisConnect(nServiceID, nConnectID);
  }
  public static void SwigDirector_ChannelListener_OnPassiveConnect(ChannelListener jself, int nSeviceID, int nConnectID) {
    jself.OnPassiveConnect(nSeviceID, nConnectID);
  }
  public static void SwigDirector_ChannelListener_OnPassiveDisConnect(ChannelListener jself, int nServiceID, int nConnectID) {
    jself.OnPassiveDisConnect(nServiceID, nConnectID);
  }
  public static void SwigDirector_ChannelListener_OnReceiveMsg(ChannelListener jself, int nServiceID, int nConnectID, byte[] pData) {
    jself.OnReceiveMsg(nServiceID, nConnectID, pData);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
