/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jggmsg;

public class SWIGTYPE_jobjectArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SWIGTYPE_jobjectArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SWIGTYPE_jobjectArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

