/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGCSHARP
#define SWIGCSHARP
#endif

#define SWIG_DIRECTORS


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_ggmsg(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_ggmsg(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_ggmsg(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else

/* -----------------------------------------------------------------------------
 * director_common.swg
 *
 * This file contains support for director classes which is common between
 * languages.
 * ----------------------------------------------------------------------------- */

/*
  Use -DSWIG_DIRECTOR_STATIC if you prefer to avoid the use of the
  'Swig' namespace. This could be useful for multi-modules projects.
*/
#ifdef SWIG_DIRECTOR_STATIC
/* Force anonymous (static) namespace */
#define Swig
#endif
/* -----------------------------------------------------------------------------
 * director.swg
 *
 * This file contains support for director classes so that C# proxy
 * methods can be called from C++.
 * ----------------------------------------------------------------------------- */

#if defined(DEBUG_DIRECTOR_OWNED)
#include <iostream>
#endif
#include <string>
#include <exception>

namespace Swig {
  /* Director base class - not currently used in C# directors */
  class Director {
  };

  /* Base class for director exceptions */
  class DirectorException : public std::exception {
  protected:
    std::string swig_msg;

  public:
    DirectorException(const char *msg) : swig_msg(msg) {
    }

    DirectorException(const std::string &msg) : swig_msg(msg) {
    }

    virtual ~DirectorException() throw() {
    }

    const char *what() const throw() {
      return swig_msg.c_str();
    }
  };

  /* Pure virtual method exception */
  class DirectorPureVirtualException : public DirectorException {
  public:
    DirectorPureVirtualException(const char *msg) : DirectorException(std::string("Attempt to invoke pure virtual method ") + msg) {
    }
  };
}

 
#include "../ggmsg/ChannelNode.h"



/* ---------------------------------------------------
 * C++ director class methods
 * --------------------------------------------------- */

#include "nggmsg.h"

SwigDirector_ChannelNode::SwigDirector_ChannelNode() : ChannelNode(), Swig::Director() {
  swig_init_callbacks();
}

void SwigDirector_ChannelNode::Start(int nServiceID, short port) {
  int jnServiceID  ;
  short jport  ;
  
  if (!swig_callbackStart) {
    throw Swig::DirectorPureVirtualException("ChannelNode::Start");
  } else {
    jnServiceID = nServiceID;
    jport = port;
    swig_callbackStart(jnServiceID, jport);
  }
}

void SwigDirector_ChannelNode::Stop() {
  if (!swig_callbackStop) {
    throw Swig::DirectorPureVirtualException("ChannelNode::Stop");
  } else {
    swig_callbackStop();
  }
}

bool SwigDirector_ChannelNode::Connect(std::string const &strHost, short sPort) {
  bool c_result = SwigValueInit< bool >() ;
  unsigned int jresult = 0 ;
  void * jstrHost = 0 ;
  short jsPort  ;
  
  if (!swig_callbackConnect) {
    throw Swig::DirectorPureVirtualException("ChannelNode::Connect");
  } else {
    jstrHost = (std::string *) &strHost; 
    jsPort = sPort;
    jresult = (unsigned int) swig_callbackConnect(jstrHost, jsPort);
    c_result = jresult ? true : false; 
  }
  return c_result;
}

int SwigDirector_ChannelNode::GetServiceID() {
  int c_result = SwigValueInit< int >() ;
  int jresult = 0 ;
  
  if (!swig_callbackGetServiceID) {
    throw Swig::DirectorPureVirtualException("ChannelNode::GetServiceID");
  } else {
    jresult = (int) swig_callbackGetServiceID();
    c_result = (int)jresult; 
  }
  return c_result;
}

bool SwigDirector_ChannelNode::SendToService(int nServiceID, void const *pData, int nDataLen) {
  bool c_result = SwigValueInit< bool >() ;
  unsigned int jresult = 0 ;
  int jnServiceID  ;
  void * jpData = 0 ;
  int jnDataLen  ;
  
  if (!swig_callbackSendToService) {
    throw Swig::DirectorPureVirtualException("ChannelNode::SendToService");
  } else {
    jnServiceID = nServiceID;
    jpData = (void *) pData; 
    jnDataLen = nDataLen;
    jresult = (unsigned int) swig_callbackSendToService(jnServiceID, jpData, jnDataLen);
    c_result = jresult ? true : false; 
  }
  return c_result;
}

bool SwigDirector_ChannelNode::SendToAllService(void const *pData, int nDataLen) {
  bool c_result = SwigValueInit< bool >() ;
  unsigned int jresult = 0 ;
  void * jpData = 0 ;
  int jnDataLen  ;
  
  if (!swig_callbackSendToAllService) {
    throw Swig::DirectorPureVirtualException("ChannelNode::SendToAllService");
  } else {
    jpData = (void *) pData; 
    jnDataLen = nDataLen;
    jresult = (unsigned int) swig_callbackSendToAllService(jpData, jnDataLen);
    c_result = jresult ? true : false; 
  }
  return c_result;
}

bool SwigDirector_ChannelNode::SendToConnect(int nConnectID, void const *pData, int nDataLen) {
  bool c_result = SwigValueInit< bool >() ;
  unsigned int jresult = 0 ;
  int jnConnectID  ;
  void * jpData = 0 ;
  int jnDataLen  ;
  
  if (!swig_callbackSendToConnect) {
    throw Swig::DirectorPureVirtualException("ChannelNode::SendToConnect");
  } else {
    jnConnectID = nConnectID;
    jpData = (void *) pData; 
    jnDataLen = nDataLen;
    jresult = (unsigned int) swig_callbackSendToConnect(jnConnectID, jpData, jnDataLen);
    c_result = jresult ? true : false; 
  }
  return c_result;
}

void SwigDirector_ChannelNode::swig_connect_director(SWIG_Callback0_t callbackStart, SWIG_Callback1_t callbackStop, SWIG_Callback2_t callbackConnect, SWIG_Callback3_t callbackGetServiceID, SWIG_Callback4_t callbackSendToService, SWIG_Callback5_t callbackSendToAllService, SWIG_Callback6_t callbackSendToConnect) {
  swig_callbackStart = callbackStart;
  swig_callbackStop = callbackStop;
  swig_callbackConnect = callbackConnect;
  swig_callbackGetServiceID = callbackGetServiceID;
  swig_callbackSendToService = callbackSendToService;
  swig_callbackSendToAllService = callbackSendToAllService;
  swig_callbackSendToConnect = callbackSendToConnect;
}

void SwigDirector_ChannelNode::swig_init_callbacks() {
  swig_callbackStart = 0;
  swig_callbackStop = 0;
  swig_callbackConnect = 0;
  swig_callbackGetServiceID = 0;
  swig_callbackSendToService = 0;
  swig_callbackSendToAllService = 0;
  swig_callbackSendToConnect = 0;
}


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void SWIGSTDCALL CSharp_nggmsg_ChannelListener_OnPositiveConnect(void * jarg1, int jarg2, int jarg3) {
  ChannelListener *arg1 = (ChannelListener *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (ChannelListener *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  (arg1)->OnPositiveConnect(arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_nggmsg_ChannelListener_OnPositiveDisConnect(void * jarg1, int jarg2, int jarg3) {
  ChannelListener *arg1 = (ChannelListener *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (ChannelListener *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  (arg1)->OnPositiveDisConnect(arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_nggmsg_ChannelListener_OnPassiveConnect(void * jarg1, int jarg2, int jarg3) {
  ChannelListener *arg1 = (ChannelListener *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (ChannelListener *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  (arg1)->OnPassiveConnect(arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_nggmsg_ChannelListener_OnPassiveDisConnect(void * jarg1, int jarg2, int jarg3) {
  ChannelListener *arg1 = (ChannelListener *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (ChannelListener *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  (arg1)->OnPassiveDisConnect(arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_nggmsg_ChannelListener_OnReceiveMsg(void * jarg1, int jarg2, int jarg3, void * jarg4, int jarg5) {
  ChannelListener *arg1 = (ChannelListener *) 0 ;
  int arg2 ;
  int arg3 ;
  void *arg4 = (void *) 0 ;
  int arg5 ;
  
  arg1 = (ChannelListener *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (void *)jarg4; 
  arg5 = (int)jarg5; 
  (arg1)->OnReceiveMsg(arg2,arg3,(void const *)arg4,arg5);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_nggmsg_new_ChannelListener() {
  void * jresult ;
  ChannelListener *result = 0 ;
  
  result = (ChannelListener *)new ChannelListener();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_nggmsg_delete_ChannelListener(void * jarg1) {
  ChannelListener *arg1 = (ChannelListener *) 0 ;
  
  arg1 = (ChannelListener *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_nggmsg_ChannelNode_Create(void * jarg1) {
  void * jresult ;
  ChannelListener *arg1 = (ChannelListener *) 0 ;
  ChannelNode *result = 0 ;
  
  arg1 = (ChannelListener *)jarg1; 
  result = (ChannelNode *)ChannelNode::Create(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_nggmsg_ChannelNode_Destory(void * jarg1) {
  ChannelNode *arg1 = (ChannelNode *) 0 ;
  
  arg1 = (ChannelNode *)jarg1; 
  ChannelNode::Destory(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_nggmsg_ChannelNode_Start(void * jarg1, int jarg2, short jarg3) {
  ChannelNode *arg1 = (ChannelNode *) 0 ;
  int arg2 ;
  short arg3 ;
  
  arg1 = (ChannelNode *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (short)jarg3; 
  (arg1)->Start(arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_nggmsg_ChannelNode_Stop(void * jarg1) {
  ChannelNode *arg1 = (ChannelNode *) 0 ;
  
  arg1 = (ChannelNode *)jarg1; 
  (arg1)->Stop();
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_nggmsg_ChannelNode_Connect(void * jarg1, void * jarg2, short jarg3) {
  unsigned int jresult ;
  ChannelNode *arg1 = (ChannelNode *) 0 ;
  std::string *arg2 = 0 ;
  short arg3 ;
  bool result;
  
  arg1 = (ChannelNode *)jarg1; 
  arg2 = (std::string *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "std::string const & type is null", 0);
    return 0;
  } 
  arg3 = (short)jarg3; 
  result = (bool)(arg1)->Connect((std::string const &)*arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_nggmsg_ChannelNode_GetServiceID(void * jarg1) {
  int jresult ;
  ChannelNode *arg1 = (ChannelNode *) 0 ;
  int result;
  
  arg1 = (ChannelNode *)jarg1; 
  result = (int)(arg1)->GetServiceID();
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_nggmsg_ChannelNode_SendToService(void * jarg1, int jarg2, void * jarg3, int jarg4) {
  unsigned int jresult ;
  ChannelNode *arg1 = (ChannelNode *) 0 ;
  int arg2 ;
  void *arg3 = (void *) 0 ;
  int arg4 ;
  bool result;
  
  arg1 = (ChannelNode *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (void *)jarg3; 
  arg4 = (int)jarg4; 
  result = (bool)(arg1)->SendToService(arg2,(void const *)arg3,arg4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_nggmsg_ChannelNode_SendToAllService(void * jarg1, void * jarg2, int jarg3) {
  unsigned int jresult ;
  ChannelNode *arg1 = (ChannelNode *) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  bool result;
  
  arg1 = (ChannelNode *)jarg1; 
  arg2 = (void *)jarg2; 
  arg3 = (int)jarg3; 
  result = (bool)(arg1)->SendToAllService((void const *)arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_nggmsg_ChannelNode_SendToConnect(void * jarg1, int jarg2, void * jarg3, int jarg4) {
  unsigned int jresult ;
  ChannelNode *arg1 = (ChannelNode *) 0 ;
  int arg2 ;
  void *arg3 = (void *) 0 ;
  int arg4 ;
  bool result;
  
  arg1 = (ChannelNode *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (void *)jarg3; 
  arg4 = (int)jarg4; 
  result = (bool)(arg1)->SendToConnect(arg2,(void const *)arg3,arg4);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_nggmsg_new_ChannelNode() {
  void * jresult ;
  ChannelNode *result = 0 ;
  
  result = (ChannelNode *)new SwigDirector_ChannelNode();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_nggmsg_delete_ChannelNode(void * jarg1) {
  ChannelNode *arg1 = (ChannelNode *) 0 ;
  
  arg1 = (ChannelNode *)jarg1; 
  delete arg1;
}


SWIGEXPORT void SWIGSTDCALL CSharp_nggmsg_ChannelNode_director_connect(void *objarg, SwigDirector_ChannelNode::SWIG_Callback0_t callback0, SwigDirector_ChannelNode::SWIG_Callback1_t callback1, SwigDirector_ChannelNode::SWIG_Callback2_t callback2, SwigDirector_ChannelNode::SWIG_Callback3_t callback3, SwigDirector_ChannelNode::SWIG_Callback4_t callback4, SwigDirector_ChannelNode::SWIG_Callback5_t callback5, SwigDirector_ChannelNode::SWIG_Callback6_t callback6) {
  ChannelNode *obj = (ChannelNode *)objarg;
  SwigDirector_ChannelNode *director = dynamic_cast<SwigDirector_ChannelNode *>(obj);
  if (director) {
    director->swig_connect_director(callback0, callback1, callback2, callback3, callback4, callback5, callback6);
  }
}


#ifdef __cplusplus
}
#endif

