/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_ggmsg_WRAP_H_
#define SWIG_ggmsg_WRAP_H_

class SwigDirector_ChannelNode : public ChannelNode, public Swig::Director {

public:
    SwigDirector_ChannelNode();
    virtual void Start(int nServiceID, short port);
    virtual void Stop();
    virtual bool Connect(std::string const &strHost, short sPort);
    virtual int GetServiceID();
    virtual bool SendToService(int nServiceID, void const *pData, int nDataLen);
    virtual bool SendToAllService(void const *pData, int nDataLen);
    virtual bool SendToConnect(int nConnectID, void const *pData, int nDataLen);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(int, short);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback2_t)(void *, short);
    typedef int (SWIGSTDCALL* SWIG_Callback3_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback4_t)(int, void *, int);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback5_t)(void *, int);
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback6_t)(int, void *, int);
    void swig_connect_director(SWIG_Callback0_t callbackStart, SWIG_Callback1_t callbackStop, SWIG_Callback2_t callbackConnect, SWIG_Callback3_t callbackGetServiceID, SWIG_Callback4_t callbackSendToService, SWIG_Callback5_t callbackSendToAllService, SWIG_Callback6_t callbackSendToConnect);

private:
    SWIG_Callback0_t swig_callbackStart;
    SWIG_Callback1_t swig_callbackStop;
    SWIG_Callback2_t swig_callbackConnect;
    SWIG_Callback3_t swig_callbackGetServiceID;
    SWIG_Callback4_t swig_callbackSendToService;
    SWIG_Callback5_t swig_callbackSendToAllService;
    SWIG_Callback6_t swig_callbackSendToConnect;
    void swig_init_callbacks();
};


#endif
