//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace nggmsg {

public class ChannelNode : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ChannelNode(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ChannelNode obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ChannelNode() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ggmsgPINVOKE.delete_ChannelNode(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public static ChannelNode Create(ChannelListener pListener) {
    global::System.IntPtr cPtr = ggmsgPINVOKE.ChannelNode_Create(ChannelListener.getCPtr(pListener));
    ChannelNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChannelNode(cPtr, false);
    return ret;
  }

  public static void Destory(ChannelNode pNode) {
    ggmsgPINVOKE.ChannelNode_Destory(ChannelNode.getCPtr(pNode));
  }

  public virtual void Start(int nServiceID, short port) {
    ggmsgPINVOKE.ChannelNode_Start(swigCPtr, nServiceID, port);
  }

  public virtual void Stop() {
    ggmsgPINVOKE.ChannelNode_Stop(swigCPtr);
  }

  public virtual bool Connect(SWIGTYPE_p_std__string strHost, short sPort) {
    bool ret = ggmsgPINVOKE.ChannelNode_Connect(swigCPtr, SWIGTYPE_p_std__string.getCPtr(strHost), sPort);
    if (ggmsgPINVOKE.SWIGPendingException.Pending) throw ggmsgPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int GetServiceID() {
    int ret = ggmsgPINVOKE.ChannelNode_GetServiceID(swigCPtr);
    return ret;
  }

  public virtual bool SendToService(int nServiceID, SWIGTYPE_p_void pData, int nDataLen) {
    bool ret = ggmsgPINVOKE.ChannelNode_SendToService(swigCPtr, nServiceID, SWIGTYPE_p_void.getCPtr(pData), nDataLen);
    return ret;
  }

  public virtual bool SendToAllService(SWIGTYPE_p_void pData, int nDataLen) {
    bool ret = ggmsgPINVOKE.ChannelNode_SendToAllService(swigCPtr, SWIGTYPE_p_void.getCPtr(pData), nDataLen);
    return ret;
  }

  public virtual bool SendToConnect(int nConnectID, SWIGTYPE_p_void pData, int nDataLen) {
    bool ret = ggmsgPINVOKE.ChannelNode_SendToConnect(swigCPtr, nConnectID, SWIGTYPE_p_void.getCPtr(pData), nDataLen);
    return ret;
  }

  public ChannelNode() : this(ggmsgPINVOKE.new_ChannelNode(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("Start", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateChannelNode_0(SwigDirectorStart);
    if (SwigDerivedClassHasMethod("Stop", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateChannelNode_1(SwigDirectorStop);
    if (SwigDerivedClassHasMethod("Connect", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateChannelNode_2(SwigDirectorConnect);
    if (SwigDerivedClassHasMethod("GetServiceID", swigMethodTypes3))
      swigDelegate3 = new SwigDelegateChannelNode_3(SwigDirectorGetServiceID);
    if (SwigDerivedClassHasMethod("SendToService", swigMethodTypes4))
      swigDelegate4 = new SwigDelegateChannelNode_4(SwigDirectorSendToService);
    if (SwigDerivedClassHasMethod("SendToAllService", swigMethodTypes5))
      swigDelegate5 = new SwigDelegateChannelNode_5(SwigDirectorSendToAllService);
    if (SwigDerivedClassHasMethod("SendToConnect", swigMethodTypes6))
      swigDelegate6 = new SwigDelegateChannelNode_6(SwigDirectorSendToConnect);
    ggmsgPINVOKE.ChannelNode_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4, swigDelegate5, swigDelegate6);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(ChannelNode));
    return hasDerivedMethod;
  }

  private void SwigDirectorStart(int nServiceID, short port) {
    Start(nServiceID, port);
  }

  private void SwigDirectorStop() {
    Stop();
  }

  private bool SwigDirectorConnect(global::System.IntPtr strHost, short sPort) {
    return Connect(new SWIGTYPE_p_std__string(strHost, false), sPort);
  }

  private int SwigDirectorGetServiceID() {
    return GetServiceID();
  }

  private bool SwigDirectorSendToService(int nServiceID, global::System.IntPtr pData, int nDataLen) {
    return SendToService(nServiceID, (pData == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(pData, false), nDataLen);
  }

  private bool SwigDirectorSendToAllService(global::System.IntPtr pData, int nDataLen) {
    return SendToAllService((pData == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(pData, false), nDataLen);
  }

  private bool SwigDirectorSendToConnect(int nConnectID, global::System.IntPtr pData, int nDataLen) {
    return SendToConnect(nConnectID, (pData == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(pData, false), nDataLen);
  }

  public delegate void SwigDelegateChannelNode_0(int nServiceID, short port);
  public delegate void SwigDelegateChannelNode_1();
  public delegate bool SwigDelegateChannelNode_2(global::System.IntPtr strHost, short sPort);
  public delegate int SwigDelegateChannelNode_3();
  public delegate bool SwigDelegateChannelNode_4(int nServiceID, global::System.IntPtr pData, int nDataLen);
  public delegate bool SwigDelegateChannelNode_5(global::System.IntPtr pData, int nDataLen);
  public delegate bool SwigDelegateChannelNode_6(int nConnectID, global::System.IntPtr pData, int nDataLen);

  private SwigDelegateChannelNode_0 swigDelegate0;
  private SwigDelegateChannelNode_1 swigDelegate1;
  private SwigDelegateChannelNode_2 swigDelegate2;
  private SwigDelegateChannelNode_3 swigDelegate3;
  private SwigDelegateChannelNode_4 swigDelegate4;
  private SwigDelegateChannelNode_5 swigDelegate5;
  private SwigDelegateChannelNode_6 swigDelegate6;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(int), typeof(short) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes2 = new global::System.Type[] { typeof(SWIGTYPE_p_std__string), typeof(short) };
  private static global::System.Type[] swigMethodTypes3 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes4 = new global::System.Type[] { typeof(int), typeof(SWIGTYPE_p_void), typeof(int) };
  private static global::System.Type[] swigMethodTypes5 = new global::System.Type[] { typeof(SWIGTYPE_p_void), typeof(int) };
  private static global::System.Type[] swigMethodTypes6 = new global::System.Type[] { typeof(int), typeof(SWIGTYPE_p_void), typeof(int) };
}

}
