//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace nggmsg {

public class ChannelListener : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ChannelListener(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ChannelListener obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ChannelListener() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ggmsgPINVOKE.delete_ChannelListener(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual void OnPositiveConnect(int nServiceID, int nConnectID) {
    ggmsgPINVOKE.ChannelListener_OnPositiveConnect(swigCPtr, nServiceID, nConnectID);
  }

  public virtual void OnPositiveDisConnect(int nServiceID, int nConnectID) {
    ggmsgPINVOKE.ChannelListener_OnPositiveDisConnect(swigCPtr, nServiceID, nConnectID);
  }

  public virtual void OnPassiveConnect(int nSeviceID, int nConnectID) {
    ggmsgPINVOKE.ChannelListener_OnPassiveConnect(swigCPtr, nSeviceID, nConnectID);
  }

  public virtual void OnPassiveDisConnect(int nServiceID, int nConnectID) {
    ggmsgPINVOKE.ChannelListener_OnPassiveDisConnect(swigCPtr, nServiceID, nConnectID);
  }

  public virtual void OnReceiveMsg(int nServiceID, int nConnectID, SWIGTYPE_p_void pMsg, int nMsgLen) {
    ggmsgPINVOKE.ChannelListener_OnReceiveMsg(swigCPtr, nServiceID, nConnectID, SWIGTYPE_p_void.getCPtr(pMsg), nMsgLen);
  }

  public ChannelListener() : this(ggmsgPINVOKE.new_ChannelListener(), true) {
  }

}

}
